// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	users "immersiveApp/features/users"

	mock "github.com/stretchr/testify/mock"
)

// AuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type AuthServiceInterface struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: id, old, new, confirm
func (_m *AuthServiceInterface) ChangePassword(id uint, old string, new string, confirm string) error {
	ret := _m.Called(id, old, new, confirm)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string, string, string) error); ok {
		r0 = rf(id, old, new, confirm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email, password
func (_m *AuthServiceInterface) Login(email string, password string) (string, error) {
	ret := _m.Called(email, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: request
func (_m *AuthServiceInterface) Register(request users.UserEntity) error {
	ret := _m.Called(request)

	var r0 error
	if rf, ok := ret.Get(0).(func(users.UserEntity) error); ok {
		r0 = rf(request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAuthServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthServiceInterface creates a new instance of AuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthServiceInterface(t mockConstructorTestingTNewAuthServiceInterface) *AuthServiceInterface {
	mock := &AuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
